set -e and some more output.

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -1,5 +1,7 @@
 #! /bin/sh
 
+set -e
+echo "Initial preparation...this can take awhile, so sit tight..."
 aclocal
 libtoolize --automake --copy --force
 autoheader
